name: TemporaryTorch
main: com.NguyenDevs.temporaryTorch.TemporaryTorch
version: ${version}
api-version: "1.21"
commands:
  tt:
    description: TemporaryTorch admin command
    usage: /tt reload
    permission: temporarytorch.admin
permissions:
  temporarytorch.use:
    default: true
  temporarytorch.admin:
    default: op
  temporarytorch.refuel:
    default: true
